services:
  soundcloak:
    container_name: soundcloak
    restart: unless-stopped
    build: .
    init: true
    ports:
      - "127.0.0.1:4664:4664"
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    volumes:
      - ./soundcloak.json:/soundcloak.json
    # Or configure with env variables:
    #environment:
    #  SOUNDCLOAK_CONFIG: 'FROM_ENV' # important to have this, otherwise config loads from json file
    #  CODEGEN_CONFIG: 'true'
    #  DEFAULT_PREFERENCES: '{"ShowAudio": true}'
    #  PROXY_IMAGES: 'true'
    #  PROXY_STREAMS: 'true'
    #  RESTREAM: 'true'
