
// Code generated by hands
// Run templ generate to generate the real code
package sc

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import (
	"git.maid.zone/stuff/soundcloak/lib/cfg"
	"github.com/a-h/templ"
)

func TrackDescription(prefs cfg.Preferences, t *Track, href string) templ.Component {
	return templ.NopComponent
}

